# Generated by Django 4.1.4 on 2022-12-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_siteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(max_length=50)),
                ('subheading', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='header', max_length=255)),
                ('subheader', models.CharField(default='subheader', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
